# Generated by Django 5.2.7 on 2025-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мероприятие (Протокол)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='Ответственный')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
            ],
        ),
    ]
