# Generated by Django 5.2.7 on 2025-11-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='protocol',
            field=models.CharField(verbose_name='Мероприятие (Протокол)'),
        ),
    ]
