# Generated by Django 5.2.7 on 2025-11-05 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_check_time', models.TimeField(default=datetime.time(9, 0))),
                ('reminder_interval', models.IntegerField(default=5)),
            ],
        ),
    ]
