# Generated by Django 5.2.7 on 2025-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='under_control',
            field=models.BooleanField(default=True, verbose_name='Под контролем'),
        ),
    ]
